
name: arbox_get_data

on:
  schedule:
    - cron: "0 7 * * *"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  get_data:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: run script
      env:
        AC_SI: ${{ secrets.AC_SI }}
        AU_TO: ${{ secrets.AU_TO }}
        MAIL: ${{ secrets.MAIL }}
        PASS: ${{ secrets.PASS }}
        FACBOOK_TOKEN_PERMENENT: ${{secrets.FACBOOK_TOKEN_PERMENENT}}
        JF_API: ${{ secrets.JF_API }}



      run: |
        cd arbox/daily_data
        python3 get_data.py
        
