
name: day_38_git

on:
  schedule:
    - cron: "17 * * * *"
  workflow_dispatch:
    inputs:
      naama:
        type: string
        description: stam

jobs:
  the_one_and_only:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: run script
      run: |
        cd day_38
        python main.py
        
