
name: Python script

on:
  schedule:
    - cron: "0 23 * * *"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  get_data:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: run script
      env:
        AC_SI: ${{ secrets.AC_SI }}
        AU_TO: ${{ secrets.AU_TO }}
        MAIL: ${{ secrets.MAIL }}
        PASS: ${{ secrets.PASS }}
      run: |
        cd arbox/daily_data
        python get_data.py
        
